name = "RNAForecaster"
uuid = "89c3ded9-0a88-4470-ac19-d41b58fa4c14"
authors = ["Rossin Erbe <rossinerbe@gmail.com>"]
version = "0.9.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DiffEqFlux = "aae7a2af-3d4f-5e19-a356-7da93b79d9d0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearRegression = "92481ed7-9fb7-40fd-80f2-46fd0f076581"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1.6"
CUDA = "3.9.0"
CategoricalArrays = "0.10.5"
DataFrames = "1.3.3"
DiffEqFlux = "1.46.0"
DifferentialEquations = "7.1.0"
Distances ="0.10.7"
Flux = "0.13.0"
HypothesisTests = "0.10.10"
JLD2 = "0.4.22"
LinearRegression = "0.2.1"
StatsBase = "0.33.16"
